<?php
/*
Plugin Name: #Haysky Code Receiver Plugin
Plugin URI: https://www.haysky.com/
Description: This plugin code is generated by Haysky Code Generator.
Version: 0.1
Author: Sufyan
Author URI: https://www.sufyan.in/
License: GPLv2 or later
Text Domain: haysky
*/
//$wpdb->show_errors(); $wpdb->print_error();

add_action('admin_menu' , function(){
    add_menu_page('Haysky Code Receiver','Haysky Code Receiver','manage_options', 'haysky_code_receiver_admin', 'haysky_code_receiver_ezq', 'dashicons-admin-users','2');
});

function haysky_code_receiver_ezq(){ include 'haysky_code_receiver.php'; }

include 'rest_api.php';
?>
